# Generated by Django 5.0.1 on 2024-03-01 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skins', '0002_alter_skin_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_skin', models.ImageField(blank=True, null=True, upload_to='profiles/heads')),
                ('skin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skins.skin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
