# Generated by Django 5.0.1 on 2024-03-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('skins', '0003_skin_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes_skins',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='skins.skin'),
        ),
    ]
