# Generated by Django 5.0.1 on 2024-03-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile_likes_skins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='head_skin',
        ),
    ]
