# Generated by Django 5.0.1 on 2024-03-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('skins', '0002_alter_skin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='members.profile'),
        ),
    ]
